#!/bin/bash
# $Id: chklogs,v 1.6 2016/11/07 16:32:50 fulford Exp fulford $
# $Source: /src/merlin/usr/local/etc/RCS/chklogs,v $
# $Revision: 1.6 $
# Author C W Fulford.
# Copyright 2016 (c) C W Fulford.
# Licensed for public use under the LGPL, .
# For assistance contact fulford@fulford.net 0793 572 8612
########################################################################
cmd=`basename $0`
ver=`echo "$Id: chklogs,v 1.6 2016/11/07 16:32:50 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
syntax="$cmd [[-c <configfile>] [-d][-v]|-V] <hostid>"
while [ $# -gt 0 ] ;do
	case $1 in 
		-c) config=$2;shift 2;;
		-d) set -x;debug=0;shift;;
		-v) verbose=:;shift;;
		-V) echo "$cmd $Revision: 1.6 $ $Date: 2016/11/07 16:32:50 $"|awk '{print $1,$3,$6}';exit;;  
		*) hostid=$1;shift;;
	esac
done
[ -n "$hostid" ] &&{ echo $syntax >&2;exit 1 ;}
config=${config:-/usr/local/etc/${cmd}.cf}
[ -r $config ]||{echo "$cmd: Can\'t find $config";exit 1}
eval `sed <$config -ne "/^$hostid:/,/^$/{/^[\t ]*[^#].*/p}"`

cd $tdir
for log in $logfiles ;do
	scp $host:$logfile `basename $f`
done
for f in *;do
	case $f in 
		bflsync) grep failed $f && {
			mailx fulford -s "URGENT - Problems with $f on $host" <$f
		;;
	esac
done
	 
