#!/bin/bash
# $Id: chklogs,v 1.11 2016/11/11 15:28:42 fulford Exp $
# $Source: /src/merlin/usr/local/etc/RCS/chklogs,v $
# $Revision: 1.11 $
# Author C W Fulford.
# Copyright 2016 (c) C W Fulford.
# Licensed for public use under the LGPL, .
# For assistance contact fulford@fulford.net 0793 572 8612
########################################################################
cmd=`basename $0`
ver=`echo "$Id: chklogs,v 1.11 2016/11/11 15:28:42 fulford Exp $"|awk '{print $3,$4,$5}'`
syntax="$cmd [[-c <configfile>] [-d][-v]|-V] <hostid>"
tdir=/tmp/$cmd;mkdir $tdir
while [ $# -gt 0 ] ;do
	case $1 in 
		-c) config=$2;shift 2;;
		-d) set -x;debug=0;shift;;
		-v) verbose=:;shift;;
		-V) echo "$cmd $Revision: 1.11 $ $Date: 2016/11/11 15:28:42 $"|awk '{print $1,$3,$6}';exit;;  
		*) hostid=$1;shift;;
	esac
done
[ -z "$hostid" ] &&{
	 echo $syntax >&2;exit 1
}
config=${config:-/usr/local/etc/${cmd}.cf}
[ -r $config ]||{
	echo "$cmd: Can\'t find $config"
	exit
}
eval `sed <$config -ne "/^$hostid:/,/^$/{/^[\t ][^#]*/p}"`

cd $tdir || {
	echo "$cmd: Could not change to directory $tdit" >&2
	exit 1
}
for log in $logfiles ;do
	tlog=`basename $log`
	scp -P227 $hostid:$log `basename $tlog` 
done
for f in *;do
	case $f in 
	bflsync) grep -q failed $f  && {
		mailx -s "URGENT - Problems with $f on $hostid" fulford <$f
		}
		;;
	esac
done
rm -r $tdir
	 
